"""Utility modules for bssunfold package.

This subpackage provides utility functions for data validation,
conversion, interpolation, and plotting.
"""

from .comparison import (
    ambient_dose_equivalent_rate,
    anderson_darling,
    chi_squared,
    compare_multiple,
    compare_spectra,
    cosine_similarity,
    cressie_read,
    cross_entropy,
    dose_averaged_energy,
    energy_dist,
    energy_group_fluence,
    entropy,
    entropy_difference_percent,
    fluence_averaged_energy,
    freeman_tukey,
    g_test,
    kl_divergence,
    kolmogorov_smirnov_stat,
    mannwhitneyu_test,
    mape,
    max_error,
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    mmd_rbf,
    pearson_r,
    r2_score,
    root_mean_squared_error,
    spearman_r,
    standardized_mean_difference,
    wasserstein_dist,
    wilcoxon_test,
)
from .converters import (
    convert_sensitivities_to_matrix,
    convert_to_dataframe,
    convert_to_dict,
    extract_detector_names,
    round_to_sigfig,
)
from .interpolation import (
    discretize_spectra,
    interpolate_spectrum,
    resample_to_log_grid,
)
from .plotting import (
    plot_comparison,
    plot_residuals,
    plot_response_functions,
    plot_spectrum,
    plot_with_uncertainty,
)
from .validators import (
    validate_energy_grid,
    validate_readings,
    validate_response_matrix,
    validate_spectrum,
)

__all__ = [
    # validators
    "validate_readings",
    "validate_energy_grid",
    "validate_spectrum",
    "validate_response_matrix",
    # converters
    "convert_to_dataframe",
    "convert_to_dict",
    "convert_sensitivities_to_matrix",
    "extract_detector_names",
    "round_to_sigfig",
    # interpolation
    "interpolate_spectrum",
    "discretize_spectra",
    "resample_to_log_grid",
    # plotting
    "plot_spectrum",
    "plot_response_functions",
    "plot_with_uncertainty",
    "plot_residuals",
    "plot_comparison",
    # comparison
    "compare_spectra",
    "compare_multiple",
    "kl_divergence",
    "cross_entropy",
    "entropy",
    "entropy_difference_percent",
    "wasserstein_dist",
    "energy_dist",
    "kolmogorov_smirnov_stat",
    "pearson_r",
    "spearman_r",
    "mean_squared_error",
    "root_mean_squared_error",
    "mean_absolute_error",
    "mape",
    "r2_score",
    "max_error",
    "median_absolute_error",
    "cosine_similarity",
    "mmd_rbf",
    "chi_squared",
    "g_test",
    "freeman_tukey",
    "cressie_read",
    "anderson_darling",
    "standardized_mean_difference",
    "wilcoxon_test",
    "mannwhitneyu_test",
    "fluence_averaged_energy",
    "energy_group_fluence",
    "dose_averaged_energy",
    "ambient_dose_equivalent_rate",
]
