"""B-spline MLEM unfolding method with sieve regularization (MLEM-BS).

Implementation of the MLEM-BS algorithm described in V. Mazankova,
L. Torokova, D. Trunec, Z. Kopecky, Z. Matej, ``Experimental Measurement
of Neutron Flux and Its Mathematical Data Processing``, Proceedings of the
5th International Conference CNDGS'2026, Brno, Czech Republic, 7-10
September 2026, ISSN 2538-8959, https://doi.org/10.47459/cndcgs.2026.61.

The method solves the discrete Fredholm integral equation of the first kind

    n_i = sum_j R_ij x_j,   i = 1..I,                       (Eq. 2)

with Poisson-distributed counts ``n_i`` by representing the sought
spectrum as a linear combination of B-spline basis functions

    x(E) = sum_s b_s B_s(E),   s = 1..N_s,

so that the effective system matrix becomes ``RB = R @ B`` and the
B-spline coefficients ``b_s`` are found with the regularized MLEM
iteration (MLEM-BS, Eq. 4 of the paper):

    b_s^(k+1) = b_s^(k) / (sum_i (RB)_is + beta * dP/db_s)
                * sum_i (RB)_is * n_i / (sum_s' (RB)_is' b_s'^(k)),

where the penalty (Eq. 5) suppresses noise influence,

    P(b) = ||D^(2) b||_2^2,      dP/db = 2 (D^(2))^T D^(2) b,

with ``D^(2)`` the second-derivative (second finite difference) matrix.
The solution is restricted to the B-spline sieve (non-negative
coefficients), following Z. Szkutnik, ``B-splines and discretization in an
inverse problem for Poisson processes``, Journal of Multivariate Analysis
93, 198-221 (2005) -- reference [7] of the paper.  Positivity is preserved
automatically by the multiplicative MLEM update started from a
non-negative sieve projection of the initial spectrum.

Following the paper, the number of iterations and the parameters ``N_s``
(B-spline space dimension) and ``beta`` (penalty strength) are selected by
minimization of the goodness-of-fit statistic (Eq. 6):

    K_S = | sum_i (n_i - sum_s (RB)_is b_s^(k))^2
            / sum_i sum_s (RB)_is b_s^(k)  -  1 |.

The paper also estimates confidence intervals of the unfolded spectrum
with a Poisson bootstrap (Eqs. 7-9): a synthetic ensemble of response
vectors is generated by resampling the backward-reconstructed counts
``n^(0) = R x^(0)`` from Poisson distributions, each replicate is unfolded,
and the 100(1-alpha)% interval is formed from the alpha/2 and 1-alpha/2
quantiles of the bootstrap distribution (95% CI corresponds to
alpha = 0.05).

Module API (standard bssunfold solver conventions):

* ``build_bspline_basis(E_MeV, n_basis, ...)`` -- B-spline design matrix;
* ``second_difference_matrix(n)`` -- the ``D^(2)`` penalty matrix;
* ``ks_statistic(b, model)`` -- the ``K_S`` statistic of Eq. 6;
* ``solve_mlem_bs(A, b, x0, E_MeV, ...)`` -- core solver returning
  ``(spectrum, iterations, converged)``;
* ``solve_mlem_bs_full(...)`` -- the same solver returning a rich
  diagnostics dictionary (``K_S`` history, effective beta, auto-selection
  table, ...);
* ``unfold_mlem_bs(...)`` -- Detector-facing wrapper (also exposed as
  ``Detector.unfold_mlem_bs``) with optional Poisson-bootstrap confidence
  intervals.

Scaling note
------------
The absolute penalty parameter ``beta`` of Eq. 4 is problem-scale
dependent (the paper uses ``beta = 1.0e-17`` for its counting setup).
For convenience this module additionally accepts ``beta_relative``,
which defines the effective penalty as ``beta = beta_relative * s_bar``
with ``s_bar`` the mean column sum of the effective matrix ``RB``, i.e.
the penalty gradient is measured relative to the MLEM sensitivity.
Exactly one of ``beta`` / ``beta_relative`` may be provided; with neither,
``beta = 0`` (pure sieve MLEM on the B-spline parameterization).
"""

from typing import Any

import numpy as np
from scipy.interpolate import BSpline
from scipy.optimize import nnls

from ..logging_config import get_logger
from ..utils.validators import validate_system
from ._base_unfolder import run_unfolding

__all__ = [
    "AUTO_BETA_RELATIVE_GRID",
    "build_bspline_basis",
    "second_difference_matrix",
    "ks_statistic",
    "solve_mlem_bs",
    "solve_mlem_bs_full",
    "unfold_mlem_bs",
]

logger = get_logger("unfold_mlem_bs")

# Numerical floors / guards -------------------------------------------------
_TINY = 1e-300         # absolute floor for denominators
_COUNT_FLOOR = 1e-10   # floor for forward-model counts (avoids div-by-zero)

# Relative penalty strengths scanned by the KS-based auto selection
# (beta_effective = beta_relative * mean column sum of RB).
AUTO_BETA_RELATIVE_GRID: tuple[float, ...] = (0.0, 1e-4, 1e-3, 1e-2, 1e-1)

_VALID_KNOT_SPACING = ("auto", "uniform", "log")


def _resolve_knot_spacing(knot_spacing: str, E: np.ndarray) -> str:
    """Resolve ``knot_spacing='auto'`` to ``'uniform'`` or ``'log'``.

    Log-spaced interior knots are used when the energy grid spans more
    than two decades (typical for Bonner sphere grids); otherwise knots
    are uniform in energy (the linear-binned setup of the paper).
    """
    if knot_spacing not in _VALID_KNOT_SPACING:
        raise ValueError(
            f"knot_spacing must be one of {_VALID_KNOT_SPACING}, got {knot_spacing!r}"
        )
    if knot_spacing != "auto":
        return knot_spacing
    ratio = float(E.max()) / float(E.min()) if E.size and E.min() > 0 else float("inf")
    return "log" if ratio > 100.0 else "uniform"


# ---------------------------------------------------------------------------
# B-spline basis utilities
# ---------------------------------------------------------------------------


def build_bspline_basis(
    E_MeV: np.ndarray,
    n_basis: int,
    spline_order: int = 4,
    knot_spacing: str = "auto",
) -> np.ndarray:
    """Build the B-spline basis (design) matrix ``B`` on an energy grid.

    The spectrum is represented as ``x(E) = B(E) @ b`` where ``B`` is the
    matrix of B-spline basis functions evaluated at the energy bins
    (the ``B_is`` matrix of Eq. 4 context in the paper).  Clamped knot
    vectors are used, so the spline reproduces the boundary energies
    exactly and the basis forms a partition of unity (a constant
    coefficient vector reproduces a constant spectrum).

    Parameters
    ----------
    E_MeV : np.ndarray
        Energy grid (MeV), 1D, positive, strictly increasing.
    n_basis : int
        Number of B-spline basis functions ``N_s`` (dimension of the
        B-spline space).  Must be ``>= spline_order``.
    spline_order : int, optional
        Order ``p`` of the B-splines (degree = order - 1).  The paper
        uses ``p = 4`` (cubic splines).  Default: 4.
    knot_spacing : str, optional
        Placement of the interior knots: ``"auto"`` (default; log knots
        when the grid spans more than two decades, uniform knots
        otherwise), ``"uniform"`` (knots linear in energy, as
        appropriate for linear-binned spectra like the stilbene data of
        the paper) or ``"log"`` (knots uniform in log-energy,
        appropriate for logarithmically binned Bonner sphere grids
        spanning several decades).

    Returns
    -------
    np.ndarray
        Dense ``(len(E_MeV), n_basis)`` design matrix with non-negative
        entries (B-splines are non-negative).
    """
    E = np.asarray(E_MeV, dtype=np.float64).ravel()
    if E.ndim != 1 or E.size < 2:
        raise ValueError(
            f"E_MeV must be a 1D array with >= 2 points, got shape {E.shape}"
        )
    if not np.all(np.isfinite(E)):
        raise ValueError("E_MeV contains non-finite values")
    if np.any(np.diff(E) <= 0):
        raise ValueError("E_MeV must be strictly increasing")
    if np.any(E <= 0):
        raise ValueError("E_MeV must contain positive energies")

    n_basis = int(n_basis)
    spline_order = int(spline_order)
    if spline_order < 2 or spline_order > 8:
        raise ValueError(f"spline_order must be in [2, 8], got {spline_order}")
    if n_basis < spline_order:
        raise ValueError(
            f"n_basis (N_s = {n_basis}) must be >= spline_order "
            f"(p = {spline_order}) for a clamped B-spline basis"
        )
    if knot_spacing not in _VALID_KNOT_SPACING:
        raise ValueError(
            f"knot_spacing must be one of {_VALID_KNOT_SPACING}, got {knot_spacing!r}"
        )

    degree = spline_order - 1
    emin = float(E[0])
    emax = float(E[-1])
    knot_spacing = _resolve_knot_spacing(knot_spacing, E)

    n_interior = n_basis - spline_order  # from len(t) = n_basis + degree + 1
    if n_interior > 0:
        if knot_spacing == "log":
            interior = np.geomspace(emin, emax, n_interior + 2)[1:-1]
        else:
            interior = np.linspace(emin, emax, n_interior + 2)[1:-1]
    else:
        interior = np.empty(0)

    t = np.concatenate(
        (
            np.full(spline_order, emin),
            interior,
            np.full(spline_order, emax),
        )
    )

    # design_matrix requires x within [t[k], t[N-k-1]]; clip for float fuzz
    x_clipped = np.clip(E, emin, emax)
    Bm = BSpline.design_matrix(x_clipped, t, degree, extrapolate=False)
    return np.asarray(Bm.todense(), dtype=np.float64)


def second_difference_matrix(n: int) -> np.ndarray:
    """Return the second-derivative (second finite difference) matrix ``D^(2)``.

    Row ``i`` holds ``[.., 1, -2, 1, ..]`` so that ``(D^(2) b)_i``
    approximates the second derivative of the coefficient sequence.
    Used in the penalty functional ``P(b) = ||D^(2) b||_2^2`` (Eq. 5).

    Parameters
    ----------
    n : int
        Length of the coefficient vector (``n >= 3``).

    Returns
    -------
    np.ndarray
        ``(n - 2, n)`` matrix.
    """
    n = int(n)
    if n < 3:
        raise ValueError(f"second_difference_matrix requires n >= 3, got {n}")
    D = np.zeros((n - 2, n), dtype=np.float64)
    for i in range(n - 2):
        D[i, i] = 1.0
        D[i, i + 1] = -2.0
        D[i, i + 2] = 1.0
    return D


def ks_statistic(b: np.ndarray, model: np.ndarray) -> float:
    """Compute the ``K_S`` goodness-of-fit statistic of Eq. 6.

    ``K_S = | sum_i (n_i - model_i)^2 / sum_i model_i - 1 |``.

    The number of iterations, ``N_s`` and ``beta`` are selected by
    minimizing this statistic (paper, section 3).

    Parameters
    ----------
    b : np.ndarray
        Measured counts vector ``n``.
    model : np.ndarray
        Forward-model counts ``RB @ b_s^(k)``.

    Returns
    -------
    float
        Non-negative ``K_S`` value.
    """
    b = np.asarray(b, dtype=np.float64).ravel()
    model = np.asarray(model, dtype=np.float64).ravel()
    denom = float(np.sum(model))
    if denom <= _TINY:
        return float("inf")
    resid = b - model
    return abs(float(np.sum(resid * resid)) / denom - 1.0)


# ---------------------------------------------------------------------------
# Core MLEM-BS iteration
# ---------------------------------------------------------------------------


def _sieve_projection(B: np.ndarray, x0: np.ndarray) -> np.ndarray:
    """Project an initial spectrum onto the non-negative B-spline sieve.

    Solves ``min ||B b - x0||_2`` subject to ``b >= 0`` (NNLS).  Falls
    back to an unconstrained least-squares fit clipped at zero when the
    NNLS solver fails.  A constant spectrum maps to constant
    coefficients through the partition-of-unity property.
    """
    ns = B.shape[1]
    mean_x0 = float(np.mean(x0)) if x0.size else 0.0
    fallback = np.full(ns, max(mean_x0, _COUNT_FLOOR))
    try:
        b0, _ = nnls(B, x0)
    except Exception:  # pragma: no cover - numerical fallback
        b0, *_ = np.linalg.lstsq(B, x0, rcond=None)
        b0 = np.maximum(b0, 0.0)
    if not np.all(np.isfinite(b0)):
        return fallback
    if not np.any(b0 > 0):
        # pathological all-zero projection: keep the iteration alive
        return np.full(ns, max(mean_x0, _COUNT_FLOOR))
    return b0


def _resolve_beta(
    beta: float | None,
    beta_relative: float | None,
    RB: np.ndarray,
) -> tuple[float, float | None]:
    """Resolve absolute vs relative penalty strength.

    Returns ``(beta_effective, beta_relative)``.  Exactly one of the two
    inputs may be non-``None``; ``None``/``None`` means no penalty.
    """
    if beta is not None and beta_relative is not None:
        raise ValueError(
            "Provide either 'beta' (absolute, paper Eq. 4) or "
            "'beta_relative' (scaled by mean sensitivity), not both"
        )
    if beta_relative is not None:
        beta_relative = float(beta_relative)
        if beta_relative < 0:
            raise ValueError(f"beta_relative must be >= 0, got {beta_relative}")
        s_bar = float(np.mean(RB.sum(axis=0))) if RB.size else 0.0
        return beta_relative * s_bar, beta_relative
    beta_eff = 0.0 if beta is None else float(beta)
    if beta_eff < 0:
        raise ValueError(f"beta must be >= 0, got {beta_eff}")
    return beta_eff, None


def _mlem_bs_iterate(
    RB: np.ndarray,
    b: np.ndarray,
    b_coef: np.ndarray,
    pen_mat: np.ndarray | None,
    beta: float,
    max_iterations: int,
    tolerance: float,
    ks_min_mode: bool,
    ks_patience: int,
) -> tuple[np.ndarray, int, bool, list[float], np.ndarray]:
    """Run the MLEM-BS iteration (Eq. 4) on the effective system.

    Parameters
    ----------
    RB : np.ndarray
        Effective response matrix ``(I, N_s)`` (``R @ B``).
    b : np.ndarray
        Measured counts ``(I,)``.
    b_coef : np.ndarray
        Initial non-negative B-spline coefficients ``(N_s,)``.
    pen_mat : np.ndarray or None
        Matrix ``2 (D^(2))^T D^(2)`` (``None`` when ``beta == 0``).
    beta : float
        Absolute penalty strength (already resolved).
    max_iterations : int
        Iteration budget.
    tolerance : float
        Relative-change convergence tolerance on the coefficients.
    ks_min_mode : bool
        When True, track the iterate with the minimal ``K_S`` and stop
        after ``ks_patience`` iterations without improvement (the paper
        selects the iteration number by minimizing ``K_S``).
    ks_patience : int
        Patience (iterations) for the ``K_S``-based early stop.

    Returns
    -------
    Tuple[np.ndarray, int, bool, List[float]]
        ``(best_coefficients, iterations, converged, ks_history)`` where
        ``best_coefficients`` is the iterate with the minimal ``K_S``
        (in ``ks_min_mode``) or simply the last iterate otherwise.
    """
    s_s = RB.sum(axis=0)  # MLEM sensitivity: sum_i (RB)_is
    s_s_safe = np.maximum(s_s, _TINY)

    best_coef = b_coef.copy()
    best_ks = ks_statistic(b, RB @ b_coef)
    ks_history: list[float] = [best_ks]
    converged = False
    iterations = 0

    for k in range(max_iterations):
        # forward projection: sum_s' (RB)_is' b_s'^(k)
        fwd = RB @ b_coef
        fwd = np.maximum(fwd, _COUNT_FLOOR)
        ratio = b / fwd

        # multiplicative ML correction
        correction = RB.T @ ratio

        # penalized denominator: sum_i (RB)_is + beta * dP/db_s  (Eq. 4)
        if beta != 0.0 and pen_mat is not None:
            grad_P = pen_mat @ b_coef
            denom = s_s + beta * grad_P
            # one-step-late guard: fall back to the unpenalized
            # sensitivity where the penalty gradient would flip the
            # denominator non-positive (standard OSL safeguard)
            denom = np.where(denom > _TINY, denom, s_s_safe)
        else:
            denom = s_s_safe
        denom = np.maximum(denom, _TINY)

        b_new = b_coef * (correction / denom)
        b_new = np.maximum(b_new, 0.0)  # B-spline sieve: b_s >= 0

        iterations = k + 1

        # K_S statistic of the new iterate (Eq. 6)
        fwd_new = RB @ b_new
        ks = ks_statistic(b, fwd_new)
        ks_history.append(ks)

        if ks_min_mode:
            if ks < best_ks:
                best_ks = ks
                best_coef = b_new.copy()
            elif (k + 1) - _argmin_index(ks_history) >= ks_patience:
                b_coef = b_new
                break
        else:
            best_coef = b_new

        # convergence on relative coefficient change
        diff = np.linalg.norm(b_new - b_coef) / (np.linalg.norm(b_coef) + _TINY)
        b_coef = b_new
        if diff < tolerance:
            converged = True
            break

    return best_coef, iterations, converged, ks_history


def _argmin_index(values: list[float]) -> int:
    """Index of the minimum of a list (ignoring NaN as never minimal)."""
    best_i = 0
    best_v = float("inf")
    for i, v in enumerate(values):
        if np.isfinite(v) and v < best_v:
            best_v = v
            best_i = i
    return best_i


# ---------------------------------------------------------------------------
# Auto parameter selection (paper: minimize K_S over N_s, beta, iterations)
# ---------------------------------------------------------------------------


def _auto_ns_grid(
    n_energy_bins: int,
    spline_order: int,
    n_points: int = 8,
) -> list[int]:
    """Candidate ``N_s`` grid for the KS-based auto selection.

    Log-spaced candidate sizes between ``max(spline_order + 1, 8)`` and
    ``min(n_energy_bins, 150)`` (the B-spline space is not usefully larger
    than the data grid for Bonner sphere problems).
    """
    lo = max(spline_order + 1, 8)
    hi = max(min(int(n_energy_bins), 150), lo)
    if hi <= lo:
        return [lo]
    grid = np.geomspace(lo, hi, n_points)
    sizes = sorted({int(round(v)) for v in grid} | {lo, hi})
    return [v for v in sizes if v >= spline_order + 1]


def _interior_knots(
    E: np.ndarray,
    n_basis: int,
    spline_order: int,
    knot_spacing: str,
) -> np.ndarray:
    """Reconstruct the interior knot sequence of the clamped basis.

    ``knot_spacing`` must already be resolved (not ``"auto"``).
    """
    n_interior = int(n_basis) - int(spline_order)
    if n_interior <= 0:
        return np.empty(0)
    emin, emax = float(E[0]), float(E[-1])
    if knot_spacing == "log":
        return np.geomspace(emin, emax, n_interior + 2)[1:-1]
    return np.linspace(emin, emax, n_interior + 2)[1:-1]


def _chi2_pearson(b: np.ndarray, model: np.ndarray) -> float:
    """Pearson chi-square ``sum_i (n_i - model_i)^2 / model_i`` (diagnostic)."""
    b = np.asarray(b, dtype=np.float64).ravel()
    model = np.asarray(model, dtype=np.float64).ravel()
    mask = model > _COUNT_FLOOR
    if not np.any(mask):
        return float("inf")
    resid = b[mask] - model[mask]
    return float(np.sum(resid * resid / model[mask]))


# ---------------------------------------------------------------------------
# Public solvers
# ---------------------------------------------------------------------------


def solve_mlem_bs_full(
    A: np.ndarray,
    b: np.ndarray,
    x0: np.ndarray | None = None,
    E_MeV: np.ndarray | None = None,
    n_basis: int | None = None,
    spline_order: int = 4,
    beta: float | None = None,
    beta_relative: float | None = None,
    knot_spacing: str = "auto",
    max_iterations: int = 1000,
    tolerance: float = 1e-6,
    auto_params: bool = False,
    ks_patience: int = 50,
) -> dict[str, Any]:
    """Solve the unfolding problem with MLEM-BS and return diagnostics.

    Parameters
    ----------
    A : np.ndarray
        Response matrix ``(I, J)``; ``J`` must match ``len(E_MeV)``.
    b : np.ndarray
        Measured readings ``(I,)`` (Poisson-distributed counts).
    x0 : np.ndarray, optional
        Initial spectrum guess ``(J,)``.  It is projected onto the
        non-negative B-spline sieve to obtain the starting coefficients.
        A flat spectrum is used when ``None``.
    E_MeV : np.ndarray
        Energy grid ``(J,)`` (MeV), required for the B-spline basis.
    n_basis : int, optional
        Dimension ``N_s`` of the B-spline space.  Default: ``None``
        selects ``max(spline_order + 1, min(n_energy_bins // 2, 40))``.
        The paper determines ``N_s`` from the first local minimum of
        ``K_S`` (e.g. ``N_s = 200`` for the fine stilbene bins); use
        ``auto_params=True`` to reproduce that selection automatically.
    spline_order : int, optional
        B-spline order ``p`` (degree ``p - 1``); the paper uses ``p = 4``
        (cubic).  Default: 4.
    beta : float, optional
        Absolute penalty strength of Eq. 4 (paper-scale dependent;
        the paper uses ``1.0e-17`` for its counting setup).
    beta_relative : float, optional
        Scale-aware alternative: effective ``beta = beta_relative *
        mean_s(sum_i (RB)_is)``.  Exactly one of ``beta`` /
        ``beta_relative`` may be given; default (both ``None``) is no
        penalty beyond the sieve.
    knot_spacing : str, optional
        Interior knot placement, ``"auto"`` (default: log knots when the
        energy grid spans more than two decades, uniform knots
        otherwise), ``"uniform"`` or ``"log"``.
    max_iterations : int, optional
        Iteration budget (default: 1000).  With ``auto_params=True`` the
        iteration count is itself selected by minimizing ``K_S``.
    tolerance : float, optional
        Relative coefficient-change convergence tolerance (default 1e-6).
    auto_params : bool, optional
        If True, ``N_s``, the penalty strength and the iteration count
        are selected by minimization of the ``K_S`` statistic (Eq. 6)
        over candidate grids, following the paper's optimization
        procedure (default: False).
    ks_patience : int, optional
        Early-stop patience (iterations without ``K_S`` improvement)
        used in the ``K_S``-minimizing mode (default: 50).

    Returns
    -------
    Dict[str, Any]
        Diagnostics dictionary with keys:

        * ``spectrum`` -- unfolded spectrum ``(J,)`` (non-negative);
        * ``coefficients`` -- B-spline coefficients ``(N_s,)``;
        * ``iterations``, ``converged`` -- iteration info;
        * ``ks_history`` -- per-iteration ``K_S`` values (Eq. 6);
        * ``ks_final`` -- ``K_S`` of the returned solution;
        * ``chi2_pearson`` -- Pearson chi-square of the final fit;
        * ``n_basis``, ``spline_order``, ``knot_spacing`` -- basis setup;
        * ``interior_knots`` -- interior knot sequence (MeV);
        * ``beta_effective``, ``beta_relative`` -- resolved penalty;
        * ``method`` -- always ``"MLEM-BS"``;
        * ``auto_selection`` -- (when ``auto_params=True``) dict with the
          candidate table and chosen parameters.
    """
    A = np.asarray(A, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64).ravel()
    A, b, x0_in = validate_system(A, b, x0=x0, max_iterations=max_iterations,
                                  tolerance=tolerance)

    n_bins = A.shape[1]
    if E_MeV is None:
        raise ValueError("E_MeV is required to build the B-spline basis")
    E = np.asarray(E_MeV, dtype=np.float64).ravel()
    if E.size != n_bins:
        raise ValueError(
            f"Length of E_MeV ({E.size}) must match the number of "
            f"columns of A ({n_bins})"
        )
    if x0_in is None:
        x0_in = np.ones(n_bins) * 0.5
    knot_spacing = _resolve_knot_spacing(knot_spacing, E)

    # --- single configuration ------------------------------------------
    def _run_single(
        ns: int,
        beta_eff: float,
        beta_rel: float | None,
        max_iter: int,
        ks_mode: bool,
    ) -> dict[str, Any]:
        B = build_bspline_basis(E, ns, spline_order=spline_order,
                                knot_spacing=knot_spacing)
        RB = A @ B
        pen_mat = None
        if beta_eff != 0.0:
            D2 = second_difference_matrix(ns)
            pen_mat = 2.0 * (D2.T @ D2)
        b0 = _sieve_projection(B, x0_in)
        best_coef, iterations, converged, ks_history = _mlem_bs_iterate(
            RB,
            b,
            b0,
            pen_mat,
            beta_eff,
            max_iter,
            tolerance,
            ks_mode,
            ks_patience,
        )
        spectrum = B @ best_coef
        model = RB @ best_coef
        return {
            "spectrum": spectrum,
            "coefficients": best_coef,
            "iterations": int(iterations),
            "converged": bool(converged),
            "ks_history": ks_history,
            "ks_final": float(ks_history[-1]) if ks_history else float("inf"),
            "chi2_pearson": _chi2_pearson(b, model),
            "n_basis": int(ns),
            "spline_order": int(spline_order),
            "knot_spacing": knot_spacing,
            "interior_knots": _interior_knots(E, ns, spline_order, knot_spacing),
            "beta_effective": float(beta_eff),
            "beta_relative": beta_rel,
            "method": "MLEM-BS",
        }

    # --- auto selection of (N_s, beta, iterations) by minimizing K_S ----
    if auto_params:
        ns_grid = _auto_ns_grid(n_bins, spline_order)
        # cap scan iterations for tractability; final run uses the budget
        scan_iter = int(min(max_iterations, 400))
        candidates: list[dict[str, Any]] = []
        best: dict[str, Any] | None = None
        for ns in ns_grid:
            for rho in AUTO_BETA_RELATIVE_GRID:
                beta_eff = 0.0
                if rho > 0.0:
                    s_bar = float(np.mean((A @ build_bspline_basis(
                        E, ns, spline_order=spline_order,
                        knot_spacing=knot_spacing)).sum(axis=0)))
                    beta_eff = rho * s_bar
                res = _run_single(ns, beta_eff, rho if rho > 0 else 0.0,
                                  scan_iter, ks_mode=True)
                entry = {
                    "n_basis": ns,
                    "beta_relative": float(rho),
                    "ks": float(np.min(res["ks_history"])),
                    "ks_iteration": int(_argmin_index(res["ks_history"])),
                    "iterations": res["iterations"],
                }
                candidates.append(entry)
                if best is None or entry["ks"] < best["ks"]:
                    best = entry
        # final run with the full iteration budget in K_S-minimizing mode
        chosen_ns = int(best["n_basis"])
        chosen_rho = float(best["beta_relative"])
        beta_eff = 0.0
        if chosen_rho > 0.0:
            Bc = build_bspline_basis(E, chosen_ns, spline_order=spline_order,
                                     knot_spacing=knot_spacing)
            beta_eff = chosen_rho * float(np.mean((A @ Bc).sum(axis=0)))
        result = _run_single(chosen_ns, beta_eff,
                             chosen_rho if chosen_rho > 0 else 0.0,
                             max_iterations, ks_mode=True)
        result["auto_selection"] = {
            "candidates": candidates,
            "chosen": best,
            "ns_grid": ns_grid,
            "beta_relative_grid": list(AUTO_BETA_RELATIVE_GRID),
        }
        result["beta_relative"] = chosen_rho if chosen_rho > 0 else None
        result["beta_effective"] = float(beta_eff)
        return result

    # --- fixed parameters ----------------------------------------------
    if n_basis is None:
        n_basis = max(spline_order + 1, min(n_bins // 2, 40))
    beta_eff, beta_rel = _resolve_beta(beta, beta_relative, np.zeros((b.size, 1)))
    # resolve beta against the actual RB (s_bar depends on the basis)
    if beta_rel is not None:
        B = build_bspline_basis(E, int(n_basis), spline_order=spline_order,
                                knot_spacing=knot_spacing)
        beta_eff = beta_rel * float(np.mean((A @ B).sum(axis=0)))
    result = _run_single(int(n_basis), beta_eff, beta_rel, max_iterations,
                         ks_mode=False)
    return result


def solve_mlem_bs(
    A: np.ndarray,
    b: np.ndarray,
    x0: np.ndarray | None = None,
    E_MeV: np.ndarray | None = None,
    n_basis: int | None = None,
    spline_order: int = 4,
    beta: float | None = None,
    beta_relative: float | None = None,
    knot_spacing: str = "auto",
    max_iterations: int = 1000,
    tolerance: float = 1e-6,
    auto_params: bool = False,
    ks_patience: int = 50,
) -> tuple[np.ndarray, int, bool]:
    """Solve unfolding using the B-spline MLEM (MLEM-BS) algorithm.

    Convenience wrapper around :func:`solve_mlem_bs_full` returning the
    standard ``(spectrum, iterations, converged)`` tuple.  See the full
    solver for the meaning of the parameters.
    """
    result = solve_mlem_bs_full(
        A,
        b,
        x0=x0,
        E_MeV=E_MeV,
        n_basis=n_basis,
        spline_order=spline_order,
        beta=beta,
        beta_relative=beta_relative,
        knot_spacing=knot_spacing,
        max_iterations=max_iterations,
        tolerance=tolerance,
        auto_params=auto_params,
        ks_patience=ks_patience,
    )
    return result["spectrum"], result["iterations"], result["converged"]


# ---------------------------------------------------------------------------
# Poisson bootstrap confidence intervals (paper Eqs. 7-9)
# ---------------------------------------------------------------------------


def _poisson_bootstrap_ci(
    A: np.ndarray,
    x0: np.ndarray | None,
    E_MeV: np.ndarray,
    spectrum: np.ndarray,
    n_bootstrap: int,
    ci_alpha: float,
    random_state: int | None,
    solver_kwargs: dict[str, Any],
) -> dict[str, Any]:
    """Percentile bootstrap CI via Poisson resampling of the counts.

    Following Eqs. 7-9 of the paper: the backward-reconstructed counts
    ``n^(0) = A @ x^(0)`` (Eq. 8, with ``x^(0)`` the unfolded spectrum)
    define the Poisson means; each bootstrap replicate ``n*(b)`` (Eq. 9)
    is drawn independently as ``Poisson(n^(0))``, unfolded with the same
    solver configuration, and the 100(1-alpha)% interval is built from
    the alpha/2 and 1-alpha/2 quantiles of the bootstrap distribution
    (95% CI corresponds to alpha = 0.05).

    Note
    ----
    The interval quantifies the *counting-statistics* uncertainty of the
    unfolded spectrum (as in the paper, where the number of measured
    bins greatly exceeds ``N_s``).  When the system is strongly
    underdetermined (e.g. few Bonner sphere readings with a large
    basis), the systematic unfolding bias dominates and the replicate
    spread may understate the true uncertainty; in that regime prefer a
    smaller ``n_basis`` / ``auto_params=True`` selection, an informative
    ``initial_spectrum`` or an energy cutoff.

    Parameters
    ----------
    A : np.ndarray
        Response matrix ``(I, J)``.
    x0 : np.ndarray, optional
        Initial spectrum used for every replicate (same as the main
        solve); ``None`` uses a flat spectrum.
    E_MeV : np.ndarray
        Energy grid ``(J,)`` (MeV).
    spectrum : np.ndarray
        Unfolded spectrum ``x^(0)`` ``(J,)`` from the main solve.
    n_bootstrap : int
        Number of bootstrap replicates ``N_B``.
    ci_alpha : float
        Significance level (0.05 for a 95% interval).
    random_state : int, optional
        Seed for the Poisson resampling RNG.
    solver_kwargs : dict
        Additional keyword arguments forwarded to :func:`solve_mlem_bs`
        for every replicate (basis and penalty configuration).

    Returns
    -------
    Dict[str, Any]
        ``ci_low``, ``ci_high``, ``ci_level``, ``bootstrap_samples``,
        ``bootstrap_alpha``, ``bootstrap_mean``, ``bootstrap_std``.
    """
    n_bootstrap = int(n_bootstrap)
    if n_bootstrap < 1:
        raise ValueError(f"n_bootstrap must be >= 1, got {n_bootstrap}")
    if not 0.0 < float(ci_alpha) < 1.0:
        raise ValueError(f"ci_alpha must be in (0, 1), got {ci_alpha}")

    # Eq. 8: backward reconstruction of the initial count spectrum
    n0 = np.maximum(A @ np.asarray(spectrum, dtype=np.float64), 0.0)
    rng = np.random.default_rng(random_state)

    n_bins = int(np.asarray(spectrum).size)
    replicates = np.empty((n_bootstrap, n_bins), dtype=np.float64)
    for i in range(n_bootstrap):
        # Eq. 9: Poisson resampling preserving counting statistics
        n_star = rng.poisson(n0).astype(np.float64)
        x_rep, _, _ = solve_mlem_bs(A, n_star, x0=x0, E_MeV=E_MeV, **solver_kwargs)
        replicates[i] = np.asarray(x_rep, dtype=np.float64)

    ci_alpha = float(ci_alpha)
    ci_low = np.percentile(replicates, 100.0 * ci_alpha / 2.0, axis=0)
    ci_high = np.percentile(replicates, 100.0 * (1.0 - ci_alpha / 2.0), axis=0)
    return {
        "ci_low": ci_low,
        "ci_high": ci_high,
        "ci_level": float(1.0 - ci_alpha),
        "bootstrap_samples": n_bootstrap,
        "bootstrap_alpha": ci_alpha,
        "bootstrap_mean": replicates.mean(axis=0),
        "bootstrap_std": (
            replicates.std(axis=0, ddof=1) if n_bootstrap > 1 else np.zeros(n_bins)
        ),
    }


# ---------------------------------------------------------------------------
# Detector-facing wrapper
# ---------------------------------------------------------------------------


def unfold_mlem_bs(
    detector_names: list[str],
    n_energy_bins: int,
    E_MeV: np.ndarray,
    sensitivities: dict[str, np.ndarray],
    cc_icrp116: dict[str, np.ndarray],
    save_result_callback,
    readings: dict[str, float],
    initial_spectrum: np.ndarray | None = None,
    n_basis: int | None = None,
    spline_order: int = 4,
    beta: float | None = None,
    beta_relative: float | None = None,
    knot_spacing: str = "auto",
    max_iterations: int = 1000,
    tolerance: float = 1e-6,
    auto_params: bool = False,
    bootstrap_ci: bool = False,
    n_bootstrap: int = 100,
    ci_alpha: float = 0.05,
    calculate_errors: bool = False,
    noise_level: float = 0.01,
    n_montecarlo: int = 100,
    save_result: bool = False,
    random_state: int | None = None,
) -> dict[str, Any]:
    """Unfold using the B-spline MLEM method with regularization (MLEM-BS).

    Detector-facing wrapper of the Mazankova et al. MLEM-BS algorithm
    (CNDGS'2026, https://doi.org/10.47459/cndcgs.2026.61): the spectrum
    is represented in a B-spline basis (sieve restriction to
    non-negative coefficients, Szkutik 2005) and the coefficients are
    updated with the regularized MLEM iteration (Eq. 4) with the
    second-derivative penalty ``P(b) = ||D^(2) b||_2^2`` (Eq. 5).
    Optionally, the number of iterations, ``N_s`` and the penalty
    strength are selected by minimizing the ``K_S`` statistic (Eq. 6),
    and confidence intervals are estimated with a Poisson bootstrap
    (Eqs. 7-9).

    Parameters
    ----------
    detector_names : List[str]
        Names of available detectors.
    n_energy_bins : int
        Number of energy bins.
    E_MeV : np.ndarray
        Energy grid (MeV).
    sensitivities : Dict[str, np.ndarray]
        Detector sensitivity arrays.
    cc_icrp116 : Dict[str, np.ndarray]
        ICRP-116 conversion coefficients.
    save_result_callback : callable
        Callback to save result to history.
    readings : Dict[str, float]
        Detector readings.
    initial_spectrum : Optional[np.ndarray], optional
        Initial spectrum guess; projected onto the non-negative
        B-spline sieve.  Flat when ``None``.
    n_basis : Optional[int], optional
        Dimension ``N_s`` of the B-spline space; default ``None``
        selects ``max(spline_order + 1, min(n_energy_bins // 2, 40))``.
    spline_order : int, optional
        B-spline order ``p`` (default: 4, cubic, as in the paper).
    beta : Optional[float], optional
        Absolute penalty strength (paper Eq. 4; problem-scale
        dependent).
    beta_relative : Optional[float], optional
        Scale-aware penalty strength: effective ``beta = beta_relative
        * mean column sum of RB``.  Mutually exclusive with ``beta``.
    knot_spacing : str, optional
        Interior knot placement: ``"auto"`` (default; log knots for
        grids spanning more than two decades, uniform knots otherwise),
        ``"uniform"`` or ``"log"`` for logarithmically binned grids.
    max_iterations : int, optional
        Iteration budget (default: 1000).
    tolerance : float, optional
        Relative coefficient-change tolerance (default: 1e-6).
    auto_params : bool, optional
        Select iteration count, ``N_s`` and penalty strength by
        minimizing ``K_S`` (Eq. 6), following the paper's optimization
        procedure (default: False).
    bootstrap_ci : bool, optional
        Estimate confidence intervals with the Poisson bootstrap of
        Eqs. 7-9 (default: False).
    n_bootstrap : int, optional
        Number of bootstrap replicates (default: 100).
    ci_alpha : float, optional
        Significance level for the CI (default: 0.05 -> 95% interval).
    calculate_errors : bool, optional
        Calculate Monte-Carlo errors (default: False).
    noise_level : float, optional
        Noise level for Monte-Carlo (default: 0.01).
    n_montecarlo : int, optional
        Number of Monte-Carlo samples (default: 100).
    save_result : bool, optional
        Save result to history (default: False).
    random_state : int, optional
        Random seed for the bootstrap resampling.

    Returns
    -------
    Dict[str, Any]
        Standardized unfolding results dictionary enriched with the
        method diagnostics (``ks_history``, ``ks_final``,
        ``chi2_pearson``, ``n_basis``, ``spline_order``,
        ``knot_spacing``, ``interior_knots``, ``beta_effective``,
        ``beta_relative`` and, when ``auto_params=True``,
        ``auto_selection``; when ``bootstrap_ci=True``, ``ci_low``,
        ``ci_high``, ``ci_level``, ``bootstrap_samples``,
        ``bootstrap_alpha``, ``bootstrap_mean``, ``bootstrap_std``).
    """
    diag: dict[str, Any] = {}

    def solve_wrapper(A_mat: np.ndarray, b_vec: np.ndarray, **kwargs):
        out = solve_mlem_bs_full(
            A_mat,
            b_vec,
            x0=kwargs.get("x0"),
            E_MeV=E_MeV,
            n_basis=n_basis,
            spline_order=spline_order,
            beta=beta,
            beta_relative=beta_relative,
            knot_spacing=knot_spacing,
            max_iterations=max_iterations,
            tolerance=tolerance,
            auto_params=auto_params,
        )
        diag.update(
            ks_history=out["ks_history"],
            ks_final=out["ks_final"],
            chi2_pearson=out["chi2_pearson"],
            n_basis=out["n_basis"],
            spline_order=out["spline_order"],
            knot_spacing=out["knot_spacing"],
            interior_knots=out["interior_knots"],
            beta_effective=out["beta_effective"],
            beta_relative=out["beta_relative"],
            coefficients=out["coefficients"],
        )
        if "auto_selection" in out:
            diag["auto_selection"] = out["auto_selection"]
        return out["spectrum"], out["iterations"], out["converged"]

    x0_default = np.ones(n_energy_bins) * 0.5

    output = run_unfolding(
        detector_names=detector_names,
        n_energy_bins=n_energy_bins,
        E_MeV=E_MeV,
        sensitivities=sensitivities,
        cc_icrp116=cc_icrp116,
        save_result_callback=save_result_callback,
        readings=readings,
        initial_spectrum=initial_spectrum,
        default_initial=x0_default,
        solve_func=solve_wrapper,
        solve_kwargs={},
        method_name="MLEM-BS",
        extra_output=diag,
        calculate_errors=calculate_errors,
        noise_level=noise_level,
        n_montecarlo=n_montecarlo,
        random_state=random_state,
        save_result=save_result,
    )

    if bootstrap_ci:
        from ._base_unfolder import _build_system, _normalize_initial

        A_sys, _, _ = _build_system(readings, detector_names, sensitivities)
        x0_main = _normalize_initial(initial_spectrum, x0_default, n_energy_bins)
        # reuse the configuration selected/used by the main solve so that
        # every replicate is unfolded with the same algorithm settings
        solver_kwargs: dict[str, Any] = {
            "n_basis": int(diag.get("n_basis") or max(
                spline_order + 1, min(n_energy_bins // 2, 40))),
            "spline_order": int(diag.get("spline_order", spline_order)),
            "beta": float(diag.get("beta_effective") or 0.0),
            "knot_spacing": diag.get("knot_spacing", knot_spacing),
            "max_iterations": int(max_iterations),
            "tolerance": float(tolerance),
        }
        boot = _poisson_bootstrap_ci(
            A_sys,
            x0=x0_main,
            E_MeV=E_MeV,
            spectrum=output["spectrum"],
            n_bootstrap=n_bootstrap,
            ci_alpha=ci_alpha,
            random_state=random_state,
            solver_kwargs=solver_kwargs,
        )
        output.update(boot)

    return output
